import { BigNumber } from 'ethers';
import { LogType } from '../type';
export declare const weiToNumber: (wei: any, decimals?: number, decimalToDisplay?: number) => string;
export declare const numberToWei: (number: any, decimals?: number) => string;
export declare const decodePowers: (powersBytes: string) => Array<number>;
export declare const formatMultiCallBignumber: (data: any) => Array<any>;
export declare const getNormalAddress: (addresses: string[]) => Array<string>;
export declare const formatFloat: (number: number | string, decimals?: number) => string;
export declare const formatPercent: (floatNumber: any, decimals?: number) => string;
export declare const mul: (a: any, b: any, useFullwide?: boolean) => string;
export declare const sub: (a: any, b: any) => string;
export declare const div: (a: any, b: any) => string;
export declare const max: (a: any, b: any) => string;
export declare const add: (a: any, b: any) => string;
export declare const detectDecimalFromPrice: (price: number | string) => number;
export declare const parseUq128x128: (value: BigNumber, unit?: number) => number;
export declare const mergeDeep: (target: any, ...sources: any) => any;
export declare const rateToHL: (r: number, power: number, DURATION?: number) => number;
export declare const rateFromHL: (HL: number, power: number, DURATION?: number) => number;
export declare const kx: (k: number, R: BigNumber, v: BigNumber, spot: BigNumber, MARK: BigNumber) => number;
export declare const STR: (num: number | string | BigNumber) => string;
export declare const NUM: (num: number | string | BigNumber) => number;
export declare const BIG: (num: number | string | BigNumber) => BigNumber;
export declare const truncate: (num: string, decimals?: number, rounding?: boolean) => string;
export declare const round: (num: string, decimals?: number) => string;
export declare const IEW: (wei: BigNumber | string, decimals?: number, decimalsToDisplay?: number) => string;
export declare const WEI: (num: number | string, decimals?: number) => string;
export declare const DIV: (a: BigNumber, b: BigNumber, precision?: number) => string;
export declare const SHL: (a: BigNumber, b: number) => BigNumber;
export declare function compareLog(a: LogType, b: LogType): number;
export declare function mergeTwoUniqSortedLogs(a: LogType[], b: LogType[]): LogType[];
//# sourceMappingURL=helper.d.ts.map